interlynk-io/sbomasm

- cmd/assemble.go
- pkg/assemble/config.go
- pkg/assemble/interface.go
PrimaryPurpose (SPDX) and Type (CycloneDX) are necessary to make use of SBOM and is recommended by NTIA Minimum Elements. This change makes it REQUIRED in config and via command line.
> [ISSUE-12] Required type value for assembling valid SBOM

- pkg/assemble/spdx/merge.go
- pkg/assemble/spdx/utils.go
- samples/spdx/issue-56/example6-bin.spdx
- samples/spdx/issue-56/example6-lib.spdx
- samples/spdx/issue-56/example6-src.spdx
SPDX merging had a bunch of issues. 
- We were not including creators from all the merged sboms
- If the merge set of documents are included in the external doc refs, they need to be removed, as they are not external anymore. 
- For relationships if docrefs are present, means they could be from external doc refs, and if those are in the mergeset then remove them. 
- SPDX2.2 has a concept of files being part of a package, SPDX2.3 does not, fixed that. 
- pyspdxtool reports an error if filesAnalyzed is set to false, then no relationships can exist. My read on the spec does not align with this. I have left my code as is.
> 56 sbomasm creates invalid spdx

- README.md
- cmd/assemble.go
- pkg/assemble/cdx/interface.go
- pkg/assemble/cdx/merge.go
- pkg/assemble/cdx/util.go
- pkg/assemble/combiner.go
- pkg/assemble/config.go
- pkg/assemble/interface.go
- pkg/assemble/spdx/interface.go
- pkg/assemble/spdx/merge.go
This adds a new merge type for sbomasm, called "Assembly merge".  This new merge is very similar to an hierarchical merge except no dependency relationships are created.
> Add assembly sbom feature for cyclonedx

- README.md
- cmd/assemble.go
- pkg/assemble/cdx/interface.go
- pkg/assemble/cdx/merge.go
- pkg/assemble/cdx/util.go
- pkg/assemble/combiner.go
- pkg/assemble/config.go
- pkg/assemble/interface.go
- pkg/assemble/spdx/interface.go
- pkg/assemble/spdx/utils.go
Add support to set the output spec and version. We default to outputting the latest spec version, but sometimes thats not ideal, as other tools may not support it.
> Add support for output spec version

- .goreleaser.yaml
closes #95 
This PR introduces the nfpms section in the GoReleaser configuration, enabling the creation of apk, deb, and rpm packages.
> Add support for sbomasm installtion using apt,  yum

- .github/workflows/release.yml
- .goreleaser.yaml
closes https://github.com/interlynk-io/sbomasm/issues/93
The SBOM is currently generated from the binary using the sbom section of GoReleaser. [goreleaser](https://goreleaser.com/blog/supply-chain-security/) utilizes the syft tool for SBOM creation, but due to issues with syft, we are transitioning to [sbom-tool](https://github.com/microsoft/sbom-tool) for SBOM generation in our CI/CD pipeline.
> sbom generation using sbom-tool

- pkg/edit/spdx_edit.go
The current spdx edit has a bug with tool formatting.
Currently after SPDX edit:
```
Tool: trivy (0.56.1)
Tool: parlay (0.5.1)
Tool: bomctl (v0.4.1)
```
After this change
```
Tool: trivy-0.56.1
Tool: parlay-0.5.1
Tool: bomctl-v0.4.1
```
> Fix SPDX tool format

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/sbom_dev.yml
- .github/workflows/sbom_release.yml
- Dockerfile
Upgrades actions and fixes Dockerfile
> Fix ghcr builds

- pkg/assemble/cdx/util.go
closes #116 
This PR addresses the issue of attempting to access a pointer that is nil, specifically when `metadata.tools.tools` is nil, which results in an error being thrown.
> handle nil pointer

- pkg/assemble/cdx/uniq_comp_service.go
- pkg/assemble/spdx/merge.go
- pkg/assemble/spdx/utils.go
closes: https://github.com/interlynk-io/sbomasm/issues/101
This PR resolves the duplicate packages from final package list. It identifies the duplicacy of package by following:
```
PURL match: If the PURL matches, it's a duplicate; no need to check further.
CPE match: If the CPE matches, it's a duplicate; no need to check further.
Name-Version match: If the Name and Version match, it's a duplicate; no need to check further.
Checksum match: If the Checksum matches, it's a duplicate; no need to check further.
```
Reference: https://github.com/interlynk-io/sbomasm/issues/101#issuecomment-2326965065
**TODO**: To test against some more SBOMs.
> fix: remove duplicate packages from final package list

- pkg/edit/cdx_edit.go
- pkg/edit/spdx.go
- pkg/edit/spdx_edit.go
closes https://github.com/interlynk-io/sbomasm/issues/115
This PR fixes 2 things
- when sbom is edited for any subject, `document`, `primary-component`, `component-name-version`.
- If subject is a `document`, following cases are possible:
- provide tool(other tools except sbomasm) explicity
-  In this case, `sbomasm` tool is not provided. For example:
``` 
$ go run main.go edit  --subject document --tool 'trivy (0.56.1)'  --tool 'parlay (0.5.1)' --tool 'bomctl (v0.4.1)'  photon.spdx.json --output photon-default.spdx.json
```
- provide tool explicity with sbomam for different version or same version
- in this case, sbomasm is provided via `--tool` flag for different version 
```
$ go run main.go edit  --subject document --tool 'trivy (0.56.1)'  --tool 'parlay (0.5.1)' --tool 'bomctl …
```
> add sbomasm as a tool for spdx and cyclonedx

- pkg/assemble/cdx/merge.go
When the oldPc does not have a component it produces an error. This checks for it its nil and creates an empty component to work with.
> fix: Fix nil value on old component

- pkg/assemble/cdx/util.go
Fixes nil panic when `*deps.Dependencies` is `nil`.
This update includes a signed commit, as per the request in https://github.com/interlynk-io/sbomasm/pull/121
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x85cb6e]
goroutine 1 [running]:
github.com/interlynk-io/sbomasm/pkg/assemble/cdx.buildDependencyList.func1(0x46959d?, 0x7924a4?)
/home/user/p/play/sbomasm/pkg/assemble/cdx/util.go:292 +0xee
github.com/samber/lo.Map[...]({0xc000b75d00?, 0x5, 0x18}, 0xc00110f620?)
/home/user/go/pkg/mod/github.com/samber/lo@v1.47.0/slice.go:30 +0x73
github.com/interlynk-io/sbomasm/pkg/assemble/cdx.buildDependencyList({0xc000b75d00?, 0xab400e?, 0x5?}, 0xc00110faf0?) …
```
> fix: nil panic in assemble

- pkg/edit/cdx.go
- pkg/edit/cdx_edit.go
- pkg/edit/spdx.go
- pkg/edit/spdx_edit.go
closes: https://github.com/interlynk-io/sbomasm/issues/146
- For both spdx and cdx:
- If it performs editing on missing element.
- For ex:
- when tries to edit subject: `primary-component`, and primary comp is missing, then it throws an error that "it fails to edit missing primary comp"
- simialrly, when sub : `component-name-version`, and that component is missing, then it throws and error that "it fails to edit missing comp"
- In both cases, throws an error on editing missing element.
> return err on editing missing primarycomp or any comp

- README.md
- Assemle -> Assemble
- pimary -> primary
- Remove an extra code block opening
- Add language code to code blocks
- Centred arrows in the diagram
> Fix typos and formatting in README

- internal/version/version.go
- pkg/edit/spdx_edit.go
- Set the `SBOMASM_VERSION` by exporting it.
```bash
.../sbomasm on 🌿 fix/issue_152 [$?] via 🔵🦦🔵 v1.23.1  via 💎 v3.2.0 
$ export SBOMASM_VERSION=0.0.3; go run main.go edit --append --subject document --tool 'trivy (0.56.1)' --tool 'parlay (0.5.1)' --tool 'bomctl (v0.4.1)' samples/spdx/issue-67/example6-bin.spdx   --output expected1.spdx.json
.../sbomasm on 🌿 fix/issue_152 [$?] via 🔵🦦🔵 v1.23.1  via 💎 v3.2.0 
➜ cat expected1.spdx.json 
SPDXVersion: SPDX-2.3
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: hello-go-bin
DocumentNamespace: https://swinslow.net/spdx-examples/example6/hello-go-bin-v2
ExternalDocumentRef: DocumentRef-go-lib https://swinslow.net/spdx-examples/example6/go-lib-v2 SHA1:58e4a6d5745f032b9788142e49edee1b508c7ac5 …
```
> customize sbomasm version accordingly

- pkg/edit/cdx_edit.go
- pkg/edit/spdx_edit.go
The PR updates the following changes:
- Earlier `timestamp` was only updated when subject was document, but not it's regardless of the subject. 
- Earlier timestamp was also updated on the basis of specific operation i.e. `missing`. But, it should be update regardless of operation.
> update timestamp on any operation

- pkg/edit/cdx_edit.go
closes https://github.com/interlynk-io/sbomasm/issues/174
- Add the author for append edit operation in case when no author is present
For example:
```bash
go run main.go  edit --subject Document  --author "foo (foo@gmail.com)" --append  --output append-empty-list-add-author.sbom.cdx.json  sbom-with-no-author.cdx.json
```
o/p:
```json
"authors": [
{
"bom-ref": "sbomasm:dec4744a-0a82-4a22-bf5c-3c56052e536d",
"name": "foo",
"email": "foo@gmail.com"
}
],
```
Earlier, when no author was present, and tries to add it using append operation, it throes an error.
> add author in append edit operation when not present

- pkg/edit/spdx_edit.go
Closes https://github.com/interlynk-io/sbomasm/issues/175
- It overwrites all existing CPEs with new CPE.
For example:
Earlier CPEs containing SBOM:
```json
"externalRefs": [
{
"referenceCategory": "SECURITY",
"referenceType": "cpe23Type",
"referenceLocator": "cpe:2.3:a:olekukonko:tablewriter:v0.0.5:*:*:*:*:*:*:*"
},
{
"referenceCategory": "PACKAGE-MANAGER",
"referenceType": "purl",
"referenceLocator": "pkg:golang/github.com/olekukonko/tablewriter@v0.0.5"
},
{
"referenceCategory": "SECURITY",
"referenceType": "cpe23Type",
"referenceLocator": "cpe:2.3:a:bar:tablewriter:v0.0.5:*:*:*:*:*:*:*"
},
{
"referenceCategory": "SECURITY",
"referenceType": "cpe23Type",
"referenceLocator": "cpe:2.3:a:bar:tablewriter:v0.0.5:*:*:*:*:*:*:*"
}
]
},
```
Now, after running …
> overwrite all cpe by new cpe in edit default operation

- pkg/edit/spdx_edit.go
closes: https://github.com/interlynk-io/sbomasm/issues/209
- It allows addition of authors for primary component as well component along with document.
> allow authors for pc and component as well

- pkg/edit/cdx_edit.go
- pkg/edit/config.go
- pkg/edit/spdx_edit.go
closes https://github.com/interlynk-io/sbomasm/issues/211
- it validates the CDX component type and shows an error for invalid input params.
> validate type and show error on invalid input params
